# Generated by Django 2.2 on 2019-04-10 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(choices=[('Toyota', 'Toyota'), ('Mazda', 'Mazda'), ('Hyundai', 'Hyundai'), ('Honda', 'Honda'), ('Buick', 'Buick')], max_length=50, verbose_name='Марка автомобиля')),
                ('client_first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('client_last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('client_patronymic_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('date', models.DateTimeField()),
                ('technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='garage.Technician', verbose_name='Выберите специалиста')),
            ],
        ),
    ]
