version: '3'

services:
  postgres-db:
    image: postgres:11.1
    restart: always
    environment:
      POSTGRES_DB: 'garage_db'
      POSTGRES_USER: 'garage_admin'
      POSTGRES_PASSWORD: '12345678'
    volumes:
      - database1_volume:/var/lib/postgresql/data

  web:
    container_name: garage_web
    ports:
      - "8000:8000"
    build: './web'
    volumes:
      - ./web/app:/app
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - postgres-db

  nginx:
      image: nginx:1.13
      ports:
        - 80:80
      volumes:
        - ./nginx/config/nginx/conf.d:/etc/nginx/conf.d
        - static_volume:/app/static/
        - media_volume:/app/media/
      depends_on:
        - web

volumes:
  database1_volume:
  static_volume:
  media_volume:
